name: Quality check

on: [ push ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Allow gradlew to be run
        run: chmod 777 ./gradlew
      - name: Check quality using detekt
        run: ./gradlew detekt
      - name: Check quality using ktlint
        run: ./gradlew ktlintCheck
